name: unicorn_binance_rest_api
dependencies:
- python>=3.6.1
- pip:
  - certifi
  - colorama
  - cryptography
  - dateparser
  - pyOpenSSL
  - requests
  - regex<=2022.3.2
  - service-identity
  - ujson